NHL_TEAMS = [
    "Anaheim Ducks",
    "Arizona Coyotes",
    "Boston Bruins",
    "Buffalo Sabres",
    "Calgary Flames",
    "Carolina Hurricanes",
    "Chicago Blackhawks",
    "Colorado Avalanche",
    "Columbus Blue Jackets",
    "Dallas Stars",
    "Detroit Red Wings",
    "Edmonton Oilers",
    "Florida Panthers",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montreal Canadiens",
    "Nashville Predators",
    "New Jersey Devils",
    "New York Islanders",
    "New York Rangers",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "San Jose Sharks",
    "Seattle Kraken",
    "St. Louis Blues",
    "Tampa Bay Lightning",
    "Toronto Maple Leafs",
    "Vancouver Canucks",
    "Vegas Golden Knights",
    "Washington Capitals",
    "Winnipeg Jets"
    ]

NFL_TEAMS = [
    "Arizona Cardinals",
    "Atlanta Falcons",
    "Baltimore Ravens",
    "Buffalo Bills",
    "Carolina Panthers",
    "Chicago Bears",
    "Cincinnati Bengals",
    "Cleveland Browns",
    "Dallas Cowboys",
    "Denver Broncos",
    "Detroit Lions",
    "Green Bay Packers",
    "Houston Texans",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Kansas City Chiefs",
    "Las Vegas Raiders",
    "Los Angeles Chargers",
    "Los Angeles Rams",
    "Miami Dolphins",
    "Minnesota Vikings",
    "New England Patriots",
    "New Orleans Saints",
    "New York Giants",
    "New York Jets",
    "Philadelphia Eagles",
    "Pittsburgh Steelers",
    "San Francisco 49ers",
    "Seattle Seahawks",
    "Tampa Bay Buccaneers",
    "Tennessee Titans",
    "Washington Commanders"
    ]

NBA_TEAMS = [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "LA Clippers",
    "LA Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards"
    ]

EPL_TEAMS = [
    "AFC Bournemouth",
    "Aston Villa",
    "Arsenal",
    "Barnsley",
    "Birmingham City",
    "Blackburn Rovers",
    "Brentford",
    "Brighton & Hove Albion",
    "Burnley",
    "Cardiff City",
    "Charlton Athletic",
    "Chelsea",
    "Crystal Palace",
    "Derby County",
    "Everton",
    "Fulham",
    "Huddersfield Town",
    "Hull City",
    "Leeds United",
    "Leicester City",
    "Liverpool",
    "Luton Town",
    "Manchester City / Man City",
    "Manchester United / Man United",
    "Middlesbrough",
    "Millwall",
    "Newcastle United",
    "Norwich City",
    "Nottingham Forest",
    "Preston North End",
    "Queens Park Rangers",
    "Reading",
    "Sheffield United",
    "Sheffield Wednesday",
    "Southampton",
    "Stoke City",
    "Sunderland",
    "Swansea City",
    "Tottenham Hotspur",
    "Watford",
    "West Bromwich Albion",
    "West Ham United",
    "Wolves"
    ]


NCAAB_TEAMS = [
"Air Force Falcons",
"Akron Zips",
"Alabama A&M Bulldogs",
"Alabama Crimson Tide",
"Alabama State Hornets",
"Albany Great Danes",
"Alcorn State Braves",
"American Eagles",
"Appalachian State Mountaineers",
"Arizona State Sun Devils",
"Arizona Wildcats",
"Arkansas Razorbacks",
"Arkansas State Red Wolves",
"Arkansas-Pine Bluff Golden Lions",
"Army West Point Black Knights",
"Auburn Tigers",
"Austin Peay Governors",
"Ball State Cardinals",
"Baylor Bears",
"Belmont Bruins",
"Bethune-Cookman Wildcats",
"Binghamton Bearcats",
"Boise State Broncos",
"Boston College Eagles",
"Boston University Terriers",
"Bowling Green Falcons",
"Bradley Braves",
"Brown Bears",
"Bryant Bulldogs",
"Bucknell Bison",
"Buffalo Bulls",
"Butler Bulldogs",
"Cal Poly Mustangs",
"Cal State Bakersfield Roadrunners",
"Cal State Fullerton Titans",
"Cal State Northridge Matadors",
"Caldwell Cougars",
"California Golden Bears",
"Campbell Fighting Camels",
"Canisius Golden Griffins",
"Central Arkansas Bears",
"Central Connecticut Blue Devils",
"Central Florida Knights",
"Central Michigan Chippewas",
"Charleston Cougars",
"Charleston Southern Buccaneers",
"Charlotte 49ers",
"Chattanooga Mocs",
"Chicago State Cougars",
"Cincinnati Bearcats",
"Clemson Tigers",
"Cleveland State Vikings",
"Coastal Carolina Chanticleers",
"Colgate Raiders",
"Colorado Buffaloes",
"Colorado State Rams",
"Columbia Lions",
"Connecticut Huskies",
"Coppin State Eagles",
"Cornell Big Red",
"Creighton Bluejays",
"Dartmouth Big Green",
"Davidson Wildcats",
"Dayton Flyers",
"Delaware Fightin' Blue Hens",
"Delaware State Hornets",
"Denver Pioneers",
"Detroit Titans",
"Drake Bulldogs",
"Drexel Dragons",
"Duke Blue Devils",
"Duquesne Dukes",
"East Carolina Pirates",
"East Tennessee State Buccaneers",
"Eastern Illinois Panthers",
"Eastern Kentucky Colonels",
"Eastern Michigan Eagles",
"Eastern Washington Eagles",
"Elon Phoenix",
"Evansville Purple Aces",
"Fairfield Stags",
"Fairleigh Dickinson Knights",
"Florida A&M Rattlers",
"Florida Atlantic Owls",
"Florida Gators",
"Florida International Golden Panthers",
"Florida State Seminoles",
"Fordham Rams",
"Fresno State Bulldogs",
"Furman Paladins",
"Gardner-Webb Runnin' Bulldogs",
"George Mason Patriots",
"Georgetown Hoyas",
"Georgia Bulldogs",
"Georgia Southern Eagles",
"Georgia State Panthers",
"Georgia Tech Yellow Jackets",
"Gonzaga Bulldogs",
"Grambling State Tigers",
"Grand Canyon Antelopes",
"Green Bay Phoenix",
"Hampton Pirates",
"Harvard Crimson",
"Hawaii Rainbow Warriors",
"High Point Panthers",
"Hofstra Pride",
"Houston Cougars",
"Houston Baptist Huskies",
"Howard Bison",
"Idaho State Bengals",
"Idaho Vandals",
"Illinois Fighting Illini",
"Illinois State Redbirds",
"Illinois-Chicago Flames",
"Indiana Hoosiers",
"Indiana State Sycamores",
"Iona Gaels",
"Iowa Hawkeyes",
"Iowa State Cyclones",
"IUPUI Jaguars",
"Jackson State Tigers",
"Jacksonville Dolphins",
"Jacksonville State Gamecocks",
"James Madison Dukes",
"Kansas Jayhawks",
"Kansas State Wildcats",
"Kennesaw State Owls",
"Kent State Golden Flashes",
"Kentucky Wildcats",
"Lamar Cardinals",
"Lehigh Mountain Hawks",
"Liberty Flames",
"Lipscomb Bisons",
"Long Beach State 49ers",
"Long Island Sharks",
"Longwood Lancers",
"Louisiana Ragin' Cajuns",
"Louisiana Tech Bulldogs",
"Louisiana-Monroe Warhawks",
"Louisville Cardinals",
"Loyola Marymount",
"Loyola (MD) Greyhounds",
"Loyola (IL) Ramblers",
"Maine Black Bears",
"Manhattan Jaspers",
"Marist Red Foxes",
"Marquette Golden Eagles",
"Marshall Thundering Herd",
"Maryland Terrapins",
"Maryland-Baltimore County Retrievers",
"Maryland Eastern Shore Hawks",
"Massachusetts Minutemen",
"McNeese State Cowboys",
"Memphis Tigers",
"Mercer Bears",
"Miami (FL) Hurricanes",
"Miami (OH) RedHawks",
"Michigan Wolverines",
"Michigan State Spartans",
"Middle Tennessee Blue Raiders",
"Minnesota Golden Gophers",
"Mississippi State Bulldogs",
"Mississippi Valley State Delta Devils",
"Missouri Tigers",
"Missouri State Bears",
"Monmouth Hawks",
"Montana Grizzlies",
"Montana State Bobcats",
"Morehead State Eagles",
"Morgan State Bears",
"Mount St. Mary's Mountaineers",
"Murray State Racers",
"Navy Midshipmen",
"Nebraska Cornhuskers",
"Nevada Wolf Pack",
"New Hampshire Wildcats",
"New Jersey Tech Highlanders",
"New Mexico Lobos",
"New Mexico State Aggies",
"New Orleans Privateers",
"North Carolina Tar Heels",
"North Carolina A&T Aggies",
"North Carolina Central Eagles",
"North Carolina State Wolfpack",
"North Dakota Fighting Hawks",
"North Dakota State Bison",
"North Florida Ospreys",
"North Texas Mean Green",
"Northeastern Huskies",
"Northern Arizona Lumberjacks",
"Northern Colorado Bears",
"Northern Illinois Huskies",
"Northern Iowa Panthers",
"Northwestern State Demons",
"Northwestern Wildcats",
"Notre Dame Fighting Irish",
"Oakland Golden Grizzlies",
"Ohio Bobcats",
"Ohio State Buckeyes",
"Oklahoma Sooners",
"Oklahoma State Cowboys",
"Old Dominion Monarchs",
"Ole Miss Rebels",
"Oral Roberts Golden Eagles",
"Oregon Ducks",
"Oregon State Beavers",
"Pacific Tigers",
"Penn Quakers",
"Penn State Nittany Lions",
"Pepperdine Waves",
"Pittsburgh Panthers",
"Portland Pilots",
"Portland State Vikings",
"Prairie View A&M Panthers",
"Presbyterian Blue Hose",
"Princeton Tigers",
"Providence Friars",
"Purdue Boilermakers",
"Quinnipiac Bobcats",
"Radford Highlanders",
"Rhode Island Rams",
"Rice Owls",
"Richmond Spiders",
"Rider Broncs",
"Robert Morris Colonials",
"Rutgers Scarlet Knights",
"Sacramento State Hornets",
"Sacred Heart Pioneers",
"Saint Francis (PA) Red Flash",
"Saint Joseph's Hawks",
"Saint Louis Billikens",
"Saint Mary's Gaels",
"Sam Houston State Bearkats",
"Samford Bulldogs",
"San Diego Toreros",
"San Diego State Aztecs",
"San Francisco Dons",
"San Jose State Spartans",
"Santa Clara Broncos",
"Savannah State Tigers",
"Seattle Redhawks",
"Seton Hall Pirates",
"Siena Saints",
"South Alabama Jaguars",
"South Carolina Gamecocks",
"South Carolina State Bulldogs",
"South Carolina Upstate Spartans",
"South Dakota Coyotes",
"South Dakota State Jackrabbits",
"South Florida Bulls",
"Southeast Missouri State Redhawks",
"Southeastern Louisiana Lions",
"Southern Illinois Salukis",
"Southern Jaguars",
"Southern Miss Golden Eagles",
"Southern Utah Thunderbirds",
"St. Bonaventure Bonnies",
"St. John's Red Storm",
"St. Peter's Peacocks",
"Stanford Cardinal",
"Stephen F. Austin Lumberjacks",
"Stony Brook Seawolves",
"Syracuse Orange",
"TCU Horned Frogs",
"Temple Owls",
"Tennessee Volunteers",
"Tennessee State Tigers",
"Tennessee Tech Golden Eagles",
"Texas A&M Aggies",
"Texas A&M-Corpus Christi Islanders",
"Texas Longhorns",
"Texas Southern Tigers",
"Texas State Bobcats",
"Texas Tech Red Raiders",
"Toledo Rockets",
"Towson Tigers",
"Tulane Green Wave",
"Tulsa Golden Hurricane",
"UAB Blazers",
"UC Davis Aggies",
"UC Irvine Anteaters",
"UC Riverside Highlanders",
"UC Santa Barbara Gauchos",
"UCF Knights",
"UCLA Bruins",
"UMBC Retrievers",
"UNC Greensboro Spartans",
"UNC Wilmington Seahawks",
"UNLV Rebels",
"USC Trojans",
"USC Upstate Spartans",
"Utah Utes",
"Utah State Aggies",
"Utah Valley Wolverines",
"VCU Rams",
"Vanderbilt Commodores",
"Vermont Catamounts",
"Villanova Wildcats",
"Virginia Cavaliers",
"Virginia Tech Hokies",
"Wagner Seahawks",
"Wake Forest Demon Deacons",
"Washington Huskies",
"Washington State Cougars",
"Weber State Wildcats",
"West Virginia Mountaineers",
"Western Carolina Catamounts",
"Western Illinois Leathernecks",
"Western Kentucky Hilltoppers",
"Western Michigan Broncos",
"Wichita State Shockers",
"William & Mary Tribe",
"Winthrop Eagles",
"Wisconsin Badgers",
"Wofford Terriers",
"Wright State Raiders",
"Wyoming Cowboys",
"Xavier Musketeers",
"Yale Bulldogs",
"Youngstown State Penguins"
]

CBA_TEAMS = [
"Beijing Ducks",
"Beijing Royal Fighters",
"Jilin Northeast Tigers",
"Liaoning Flying Leopards",
"Qingdao Eagles",
"Shandong Hi-Speed Kirin",
"Shanxi Loongs",
"Sichuan Blue Whales",
"Tianjin Pioneers",
"Xinjiang Flying Tigers",
"Fujian Sturgeons",
"Guangdong Southern Tigers",
"Guangzhou Loong Lions",
"Jiangsu Dragons",
"Nanjing Monkey Kings",
"Ningbo Rockets",
"Shanghai Sharks",
"Shenzhen Leopards",
"Zhejiang Golden Bulls",
"Zhejiang Guangsha Lions",
]

EUROLEAGUE_TEAMS=[
    "ALBA Berlin",
    "Anadolu Efes",
    "AS Monaco Basket",
    "ASVEL Basket",
    "Barca",
    "Baskonia",
    "Bayern Munich",
    "Fenerbahce Beko",
    "KK Crvena Zvezda",
    "KK Partizan",
    "Maccabi FOX Tel Aviv",
    "Olimpia Milano",
    "Olympiacos",
    "Panathinaikos",
    "Real Madrid",
    "Valencia Basket",
    "Virtus Bologna",
    "Zalgiris",
]

LALIGA_TEAMS = [
"Almeria",
"Athletic Bilbao",
"Atletico Madrid",
"Barcelona",
"Betis",
"Cádiz CF",
"Celta Vigo",
"Elche",
"Espanyol",
"Getafe",
"Girona FC",
"Mallorca",
"Osasuna",
"Rayo Vallecano",
"Real Madrid",
"Real Sociedad",
"Real Valladolid",
"Sevilla",
"Valencia",
"Villarreal"
]

KHL_TEAMS=[
"SKA Saint Petersburg",
"HC Sochi",
"Spartak Moscow",
"Torpedo Nizhny Novgorod",
"HC Vityaz",
"CSKA Moscow",
"Dinamo Minsk",
"Dynamo Moscow",
"Red Star Kunlun",
"Lokomotiv Yaroslavl",
"Severstal Cherepovets",
"Ak Bars Kazan",
"Avtomobilist Yekaterinburg",
"Metallurg Magnitogorsk",
"Neftekhimik Nizhnekamsk",
"Traktor Chelyabinsk",
"Admiral Vladivostok",
"Amur Khabarovsk",
"Avangard Omsk",
"Barys Astana",
"Salavat Yulaev Ufa",
"Sibir Novosibirsk"
]

SHL_TEAMS=[
    "Brynäs IF",
    "Djurgårdens IF",
    "Frölunda HC",
    "Färjestad BK",
    "Leksands IF",
    "Linköping HC",
    "Luleå HF",
    "Malmö Redhawks",
    "IK Oskarshamn",
    "Rögle BK",
    "Skellefteå AIK",
    "Timrå IK",
    "Växjö Lakers",
    "Örebro HK",
]

ELH_TEAMS = [
    "Vítkovice Ridera",
    "Verva Litvínov",
    "Sparta Praha",
    "Rytíři Kladno",
    "Oceláři Třinec",
    "Mountfield HK",
    "Kometa Brno",
    "HC Škoda Plzeň",
    "HC Olomouc",
    "Energie Karlovy Vary",
    "Dynamo Pardubice",
    "ČEZ Motor České Budějovice",
    "BK Mladá Boleslav",
    "Bílí Tygři Liberec"
]

LIIGA_TEAMS = [
    "HIFK",
    "HPK",
    "Ilves",
    "Jukurit",
    "JYP",
    "KalPa",
    "KooKoo",
    "Kärpät",
    "Lukko",
    "Pelicans",
    "SaiPa",
    "Sport",
    "Tappara",
    "TPS",
    "Ässät"
]

NBL_TEAMS = [
    "Adelaide 36ers",
    "Brisbane Bullets",
    "Cairns Taipans",
    "Illawarra Hawks",
    "Melbourne United",
    "New Zealand Breakers",
    "Perth Wildcats",
    "South East Melbourne Phoenix",
    "Sydney Kings",
    "Tasmania JackJumpers"
]

CHINA_NBL_TEAMS = [
    "Anhui Putian Xingfa",
    "Anhui Wenyi",
    "Beijing Oriental Bucks",
    "Changsha Wantian Yongs",
    "Chongqing Lanling",
    "Guangxi Weizhuang",
    "Hebei Xianglan",
    "Hefei Yuanchang",
    "Henan Shedian Laojiu",
    "Hunan Jinjian Rice Industry",
    "Jiangsu Yannan Suke",
    "Luoyang Zhonghe",
    "Shaanxi Xinda",
    "Wuhan Dangdai",
    "Wuhan Kungpeng",
    "Xinjiang Tianshan Eagle"
]